---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

# Action test/validation workflow
name: "Test GitHub Action 🧪"

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions: {}

jobs:
  ### Test the GitHub Action in this Repository ###
  tests:
    name: "Action Testing"
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # Perform setup prior to running test(s)
      - name: "Checkout repository"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: "modeseven-lfreleng-actions/test-python-project"
          path: "test-python-project"

      - name: "Setup Python"
        # yamllint disable-line rule:line-length
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
        with:
          python-version-file: "pyproject.toml"
          cache: "pip"

      - name: "Build sample Python project"
        shell: bash
        run: |
          # Build sample Python project
          cd test-python-project
          python -m build

      - name: "Run Action: ${{ github.repository }}"
        uses: ./

      - name: "Validate: ${{ github.repository }}"
        shell: bash
        run: |
          # Validate local action
          echo "Validating: ${{ github.repository }}"
